# Default PoorCraft Configuration

game:
  language: en_US
  renderDistance: 8
  fov: 70

audio:
  masterVolume: 1.0
  musicVolume: 0.5
  soundVolume: 1.0

network:
  serverPort: 25565
  connectionTimeout: 30000
  maxPlayers: 20

world:
  seed: 0
  gameMode: survival
  difficulty: normal
  spawnProtectionRadius: 16
  generationThreads: 4
  meshingThreads: 2
  noiseScale: 0.003
  noiseOctaves: 6
  noiseLacunarity: 2.0
  noiseGain: 0.5
  baseHeight: 64
  heightVariation: 32
  biomeScale: 0.001
  biomeBlendRadius: 16.0
  treeChance: 0.02

mods:
  directory: mods
  autoDownload: false

window:
  width: 1280
  height: 720
  fullscreen: false
  vsync: true
  resizable: true
  title: PoorCraft

graphics:
  maxFps: 60
  quality: medium
  shadows: true
  particles: all
  openglVersion: "3.3"
  useDSA: true
  useReverseZ: false
  anisotropicFiltering: 8
  msaaSamples: 4
  flipTextures: true

input:
  mouseSensitivity: 1.0
  invertY: false
  rawMouseMotion: true
  gamepadDeadzone: 0.25

resources:
  hotReload: true
  watchDebounceMs: 150
  shaderPath: shaders
  texturePath: textures
